### ISSUE TITLE
Getting an uncaught exception in Cookie.php line no 190.

### ISSUE THREAD

**Issue by siddhantjm** [etsy/411#167]
Stack trace of the same:
Fatal error: Uncaught exception 'FOO\CookieException' with message 'Cookie secret too short' in C:\wamp64\www\411\phplib\Cookie.php:190
Stack trace:
#0 C:\wamp64\www\411\phplib\Cookie.php(91): FOO\Cookie::getKey()
#1 C:\wamp64\www\411\phplib\Cookie.php(105): FOO\Cookie::generate(Array, 1511500631)
#2 C:\wamp64\www\411\phplib\Cookie.php(33): FOO\Cookie::write()
#3 C:\wamp64\www\411\bin\create_user.php(23): FOO\Cookie::FOO\{closure}()
#4 {main}
  thrown in C:\wamp64\www\411\phplib\Cookie.php on line 190

**Comment by siddhantjm** [comment]
I'm still getting an issue on the same line of Cookie.php line no 190
